# Generated by Django 5.2.8 on 2025-11-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('author', models.CharField(default='Inconnu', max_length=150)),
                ('book_title', models.CharField(default='Inconnu', max_length=255)),
            ],
        ),
    ]
