# Generated by Django 5.2.8 on 2025-11-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvisApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avis',
            name='book',
        ),
        migrations.AlterModelOptions(
            name='avis',
            options={},
        ),
        migrations.RemoveField(
            model_name='avis',
            name='idAvis',
        ),
        migrations.RemoveField(
            model_name='avis',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='avis',
            name='user',
        ),
        migrations.AddField(
            model_name='avis',
            name='author',
            field=models.CharField(default='Inconnu', max_length=150),
        ),
        migrations.AddField(
            model_name='avis',
            name='book_title',
            field=models.CharField(default='Inconnu', max_length=255),
        ),
        migrations.AddField(
            model_name='avis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='avis',
            name='note',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
