# Generated by Django 5.2.8 on 2025-11-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Livre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("auteur", models.CharField(max_length=200)),
                (
                    "isbn",
                    models.CharField(blank=True, max_length=13, null=True, unique=True),
                ),
                ("date_publication", models.DateField(blank=True, null=True)),
                ("quantite", models.PositiveIntegerField(default=1)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="livres/"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "prix",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("disponible", models.BooleanField(default=True)),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                ("date_modif", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date_ajout"],
                "unique_together": {("titre", "auteur", "isbn")},
            },
        ),
    ]
