# Generated by Django 5.2.8 on 2025-11-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LivreApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="livre",
            options={
                "ordering": ["-date_added"],
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
            },
        ),
        migrations.RemoveConstraint(
            model_name="livre",
            name="unique_livre_combinaison",
        ),
        migrations.RenameField(
            model_name="livre",
            old_name="auteur",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="livre",
            old_name="disponible",
            new_name="available",
        ),
        migrations.RenameField(
            model_name="livre",
            old_name="date_ajout",
            new_name="date_added",
        ),
        migrations.RenameField(
            model_name="livre",
            old_name="date_modif",
            new_name="date_modified",
        ),
        migrations.RenameField(
            model_name="livre",
            old_name="prix",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="livre",
            old_name="date_publication",
            new_name="publication_date",
        ),
        migrations.RenameField(
            model_name="livre",
            old_name="quantite",
            new_name="quantity",
        ),
        migrations.RenameField(
            model_name="livre",
            old_name="titre",
            new_name="title",
        ),
        migrations.AddConstraint(
            model_name="livre",
            constraint=models.UniqueConstraint(
                fields=("title", "author", "isbn"), name="unique_book_combination"
            ),
        ),
    ]
