# Generated by Django 5.2.8 on 2025-11-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LivreApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="livre",
            options={
                "ordering": ["-date_ajout"],
                "verbose_name": "Livre",
                "verbose_name_plural": "Livres",
            },
        ),
        migrations.AlterUniqueTogether(
            name="livre",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="livre",
            name="image_blob",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="livre",
            constraint=models.UniqueConstraint(
                fields=("titre", "auteur", "isbn"), name="unique_livre_combinaison"
            ),
        ),
        migrations.RemoveField(
            model_name="livre",
            name="image",
        ),
    ]
