# Generated by Django 5.2.8 on 2025-11-18 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LivreApp', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantité en stock')),
                ('min_quantity', models.PositiveIntegerField(default=10, help_text='Seuil pour alerte stock faible', verbose_name='Quantité minimum')),
                ('max_quantity', models.PositiveIntegerField(default=100, help_text='Capacité maximale de stockage', verbose_name='Quantité maximum')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('out_of_stock', 'Rupture de stock'), ('on_order', 'En commande'), ('low', 'Stock limité')], default='available', max_length=20, verbose_name='Statut')),
                ('location', models.CharField(blank=True, help_text='Rayon, entrepôt, etc.', max_length=100, verbose_name='Emplacement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='LivreApp.livre', verbose_name='Livre')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['status'], name='StockApp_st_status_72b9d7_idx'), models.Index(fields=['book', 'location'], name='StockApp_st_book_id_c86deb_idx')],
            },
        ),
    ]
