# Generated by Django 5.2.8 on 2025-11-18 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LivreApp', '0001_initial'),
        ('StockApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stock',
            name='StockApp_st_status_72b9d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='StockApp_st_book_id_c86deb_idx',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='location',
        ),
        migrations.AlterField(
            model_name='stock',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='LivreApp.livre', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='max_quantity',
            field=models.PositiveIntegerField(default=100, help_text='Maximum storage capacity', verbose_name='Maximum Quantity'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='min_quantity',
            field=models.PositiveIntegerField(default=10, help_text='Threshold for low stock alert', verbose_name='Minimum Quantity'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity in Stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out of Stock'), ('on_order', 'On Order'), ('low', 'Low Stock')], default='available', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modification'),
        ),
    ]
