# Generated by Django 5.2.8 on 2025-11-18 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LivreApp', '0001_initial'),
        ('StockApp', '0002_remove_stock_stockapp_st_status_72b9d7_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.AlterField(
            model_name='stock',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stock', serialize=False, to='LivreApp.livre', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out of Stock'), ('on_order', 'On Order'), ('low', 'Low Stock')], default='available', editable=False, max_length=20, verbose_name='Status'),
        ),
    ]
